### ISSUE TITLE
Bug: YAML comment is removed

### ISSUE THREAD

**Issue by karmeye** [platers/obsidian-linter#660]
## Describe the Bug

A YAML comment on its own line is removed when linting. I can't find any rule that does this.

## How to Reproduce

```yaml
created: 2023-02-18T10:53:01+00:00
# Dont remove me
disabled rules: [capitalize-headings]
modified: 2023-03-20T14:53:42+00:00

```

## Expected Behavior

YAML comnents should not be removed.

## Device

- [probably] Desktop
- [x] Mobile
