### ISSUE TITLE
Question: date created and updated in nested format

### ISSUE THREAD

**Issue by andrey-jef** [platers/obsidian-linter#967]
Hi,

In the [yaml-timestamp](https://platers.github.io/obsidian-linter/settings/yaml-rules/#yaml-timestamp) rules, is it possible to lint the date created and updated to a nested format as follows?

```yaml
date:
    created: YYYY-MM-DDTHH:mm:ssZ
    updated: YYYY-MM-DDTHH:mm:ssZ
```

Thanks

**Comment by pjkaufman** [comment]
Hey @andrey-jef . Nesting keys like this is not officially supported. You might be able to get it working if you manually tinkered with the `data.json` for the Linter plugin, but that is something you would have to do at your own risk.

**Comment by andrey-jef** [comment]
Then is it possible for Linter to recognize the keys that have existed and not duplicating again?

At the moment, when I manually add the nested keys, then Linter will duplicate timestamp on the save of file
```
date:
    created:
    updated:
created:
updated:
```

And can u point me to where to read more about the data.json of Linter?

Thanks
