### ISSUE TITLE
Bug: YAML key value pair list item escaped to a string

### ISSUE THREAD

**Issue by Balibaloo** [platers/obsidian-linter#997]
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

List items that are key value pairs are treated as strings that need to be escaped.

## How to Reproduce

Linting the following list of items:
```YAML
list:
  - key: "value"
    nested_list:
      - key: "value"
  - key: "other value"
```

Results in invalid yaml:
``` YAML
list:
  - 'key: "value"'
    nested_list:
      - 'key: "value"'
  - 'key: "other value"'
```
[logs.txt](https://github.com/platers/obsidian-linter/files/13982624/logs.txt)
[config.txt](https://github.com/platers/obsidian-linter/files/13982626/config.txt)

## Expected Behavior
The linted yaml should not escape `key: value` to `"key: value"`

## Device

- [X] Desktop

## Additional Context

I feel like this issue is so simple that it should have already been raised but I couldnt find any mentions.
I just updated from 1.3.xx and it wasnt an issue then.
